export { default as ProfilePage } from './ProfilePage'
export { default as ChangePasswordPage } from './ChangePasswordPage'
export { default as ChefPage } from './ChefPage'
export { default as CreateChefPage } from './CreateChefPage'
export { default as CuisinesPage } from './CuisinesPage'
export { default as DiscountModal } from './DiscountModal'
export { default as EditProfilePage } from './EditProfilePage'
export { default as LogoutModal } from './LogoutModal'
export { default as OrderHistoryPage } from './OrderHistoryPage'
export { default as OrderWaterBottleModal } from './OrderWaterBottleModal'
export { default as ReviewModal } from './ReviewModal'
export { default as SettingPage } from './SettingPage'
export { default as SupportPage } from './SupportPage'
export { default as TermsPage } from './TermsPage'

export { default } from './ProfilePage'
